<!-- <datalist id="options">
    <option value="Rice/Palay">
    <option value="Water melon">
    <option value="Pigs or swine">
    <option value="Buffaloes (Carabaos)">
    <option value="Goats">
    <option value="Ducks">
    <option value="Chickens">
    <option value="String beans -  harvested green (sitao)">
    <option value="Patola">
    <option value="Okra">
    <option value="Eggplant (talong)">
    <option value="Batao"></option>
    <option value="Pechay"></option>
    <option value="Turkeys"></option>
    <option value="Geese"></option>
    <option value="Sheep"></option>
    <option value="Corn"></option>
    <option value="Chili (labuyo)"></option>
    <option value="Camote"></option>
    <option value="Mustard"></option>
    <option value="Mango"></option>
    <option value="Tomato (kamatis)"></option>
    <option value="Ampalaya"></option>
    <option value="Long Chili"></option>
    <option value="Mongo (Mung Bean)"></option>
    <option value="Cattle"></option>
    <option value="Common gourd (upo)"></option>
    <option value="Bush Sitao"></option>
    <option value="Winged Bean (pallang)"></option>
    <option value="Horses"></option>
    <option value="Cucumber (pipino)"></option>
    <option value="Squash (kalabasa)"></option>
    <option value="Papaya"></option>
    <option value="Rabbits and hares"></option>
    <option value="Onion bulbs (sibuyas)"></option>
    <option value="Rambutan"></option>
    <option value="Kangkong"></option>
    <option value="Quail"></option>
    <option value="Spinach"></option>
</datalist> -->