document.getElementById('fullNameDisplay').innerHTML = `Generated By: ${localStorage.getItem('fullName')}`;
window.print();
const boxes = document.querySelectorAll('.box');
let isCtrlPressed = false;

// Handle click event on each box
boxes.forEach((box) => {
  box.addEventListener('click', () => {
    if (isCtrlPressed) {
      const currentWidth = parseInt(window.getComputedStyle(box).width);
      box.style.width = `${currentWidth + 50}px`;
    } else {
      box.style.display = 'none';  // Hide the box
    }
  });
});

// Detect if the Ctrl key is being pressed
window.addEventListener('keydown', (event) => {
  if (event.key === 'Control') {
    isCtrlPressed = true;
  }
});

window.addEventListener('keyup', (event) => {
  if (event.key === 'Control') {
    isCtrlPressed = false;
  }
});